version: "3.3"

services:
    prometheus:
        image: prom/prometheus:v2.17.1
        container_name: prometheus
        volumes:
            - ./prometheus:/etc/prometheus
            - ems_dev_prometheus:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=200h'
            - '--web.enable-lifecycle'
        restart: unless-stopped
        ports:
            - "9090:9090"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        volumes:
            - ems_dev_grafana_data:/var/lib/grafana
            - ./grafana/provisioning:/etc/grafana/provisioning
        environment:
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        restart: unless-stopped
        ports:
            - "3000:3000"

volumes:
    ems_dev_prometheus: {}
    ems_dev_grafana_data: {}

networks:
    default:
        external:
            name: local-dev