global:
    scrape_interval:     15s
    evaluation_interval: 15s

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
    - job_name: 'ems'
      scrape_interval: 10s
      metrics_path: /metrics
      tls_config:
          insecure_skip_verify: true
      static_configs:
          - targets: ['host.docker.internal:8081']
      relabel_configs:
          -   source_labels: [ __address__ ]
              regex: '.*'
              target_label: instance
              replacement: 'colibri'
